[package]
name = "qchess"
version = "0.1.0"
authors = ["Gunvir Ranu <mail@gunvirranu.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
